version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: project-model
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: project-model
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789